### ISSUE TITLE
enforce HTTPS

### ISSUE THREAD

**Issue by chantra** [dns-violations/dnsflagday#119]
the website can be accessed under http://dnsflagday.net/ and does not redirect to HTTPS.

I would be nice to enforce HTTPS. CF seems to provide an [easy way to do that](https://support.cloudflare.com/hc/en-us/articles/204144518-SSL-FAQ#h_a61bfdef-08dd-40f8-8888-7edd8e40d156).

Additionally, there seems to be a few places where we should default links to HTTPS instead of HTTP. I have #118 out, but it seems the 2019 page also has http links that could be changed to https.

**Comment by Mikaela** [comment]
Is there a particular reason why Cloudflare is used? I have heard [many concerns about them](https://notabug.org/themusicgod1/cloudflare-tor/src/master/README.md).

If the site was hosted on GitHub pages directly, there would be a checkbox to enforce HTTPS, see [Securing your GitHub pages site with HTTPS](https://help.github.com/en/articles/securing-your-github-pages-site-with-https).

**Comment by jelu** [comment]
It's a GitHub pages site, will look at this tomorrow.

**Comment by jelu** [comment]
I think the reason @chantra mentioned Cloudflare is because the domain is hosted there.

We need to change the A record(s) in order to get HTTPS working and it might take some time since it's holiday season etc.

**Comment by jelu** [comment]
Apparently it is fronted by Cloudflare (didn't know) and HTTPS works now.

**Comment by Mikaela** [comment]
I noticed the Cloudflare fronting from IPv6 addresses and checked the GitHub pages documentation in hope that they had started supporting IPv6 and I just hadn't set the records, but the IPv4 addresses were also different

**Comment by jelu** [comment]
@oerdnj can you look at v6 support?
