### ISSUE TITLE
Please use gender neutral language in informational messages

### ISSUE THREAD

**Issue by fincham** [dns-violations/dnsflagday#14]
Hi folks,

I ran a test and found that the output contained the phrase "If the problem persists contact your DNS administrator and refer him...". This should be a gender neutral phrase like "them", unless you wish to imply that only men may administer DNS.

Thanks,
-Michael

**Comment by fincham** [comment]
I've created pull request #15 to fix this :)

**Comment by pspacek** [comment]
Closed by #15
