### ISSUE TITLE
Enable IPv6 for this website

### ISSUE THREAD

**Issue by philippebourcier** [dns-violations/dnsflagday#23]
Title says it all... it would be nice to have this website running dual-stack.
Github hosting doesn't support IPv6 (for whatever mysterious reasons).
So if you move this website behind a free CloudFlare account (which is a sponsor for this project it seems), it will then be IPv6-enabled... we're in 2018 after all :)

**Comment by carlosm3011** [comment]
This website needs IPv6 *badly*

**Comment by marka63** [comment]
Why does it need IPv6 badly?  The testing is being done from dual stacked machines.

**Comment by pspacek** [comment]
Someone needs to donate manpower for this. Closing until a volunteer shows up.

**Comment by carlosm3011** [comment]
If all you need is a mirror for the site that has IPv6, I can help.

**Comment by spacekpe** [comment]
We can try that - put an IPv6 address here once mirror is set up. Beware that it needs to auto-update as we change Github repo.

**Comment by carlosm3011** [comment]
I’ve done that for www.labs.lacnic.net in fact :-)

Can you get me pull/clone rights for my github account ? (carlosm3011)

**Comment by pspacek** [comment]
I'm confused - what permissions are necessary? Anyone can clone repo from https://github.com/dns-violations/dnsflagday.git .

**Comment by carlosm3011** [comment]
I have the repo mirrored in one of my serves.

I’m struggling a little bit to rebuild it, just a “jekyll build” 
is not giving me much.

```
carlos@mvuy22:/var/www/html/dnsflagday$ jekyll build --incremental
Configuration file: /var/www/html/dnsflagday/_config.yml
             Source: /var/www/html/dnsflagday
        Destination: /var/www/html/dnsflagday/_site
  Incremental build: enabled
       Generating...
                     done in 0.074 seconds.
```

No errors, but no html is generated in _site.


I’m probably missing something obvious. Any help is appreciated.

/Carlos
