### ISSUE TITLE
Document software that is not broken

### ISSUE THREAD

**Issue by laffer1** [dns-violations/dnsflagday#24]
It would be helpful to document information on adding EDNS support to your DNS servers.  What versions of bind, unbound, etc are minimums?  What ports have to be open on the firewall? (512 tcp?)

**Comment by laffer1** [comment]
add a link to this https://kb.isc.org/docs/aa-01387

**Comment by marka63** [comment]
BIND 9 has done EDNS correctly from day one.

**Comment by oerdnj** [comment]
Any supported version of open-source DNS servers does the right thing.
DNS port is 53, I am not sure what would you want to document here.

**Comment by laffer1** [comment]
The site says that some software is "broken" but doesn't have a call to action on what needs to get fixed.  You have a website with alarm bells and no clear what to do.  

Googling the problem got me a site claiming i needed port 512 open in addition to 53.  Having relevant facts on the site like bind 9 just works would save a lot of people time as they see this problem.

**Comment by oerdnj** [comment]
The site has an ability to test the domains.  You can't really say that if you deploy any DNS software you'll be fine.  There could be "smart" firewall or load-balancer in front of it and it could break it.

Henceforth, test your domains.

**Comment by pspacek** [comment]
Yeah, there is too many moving parts so it is simply impossible to list "software which works" - the problem might be elsewhere.

@laffer1 We could clarify this somehow. Could you propose specific wording to convey this message?

**Comment by laffer1** [comment]
I think the issue is that you guys are coming at it from a large provider perspective.  If someone is a hostmaster at a university or large company, they likely do have load balancers, firewalls and such.  

However, someone managing a smaller network won't have all this stuff.  I realize this is an increasingly unlikely problem in an era of cloud providers and so on but it happens.  

Would it be fair to say something like this: 

"If your site should fail the test or have issues, please check for updates to DNS server software, load balancers or smart firewalls between your DNS infrastructure and the Internet.  End of life DNS software should be replaced with modern equivalents.  "

The latter is kind of a hint about anyone using really old BIND versions.  This doesn't call out specific versions but gives a hint at least.

**Comment by pspacek** [comment]
Well, the site already says:
```
To remediate problems please upgrade your DNS software to the latest stable versions and test again. If the tests are still failing even after a DNS upgrade please check your firewall configuration.
```

What am I missing?

**Comment by pspacek** [comment]
Response timeout, closing.
