### ISSUE TITLE
server is down

### ISSUE THREAD

**Issue by kruisdraad** [dns-violations/dnsflagday#32]
due to the lack of other contact info:

test server is down, the ednscomp tool, dnsflagday used this thru API and therefor that tool is not working either.

**Comment by vcunat** [comment]
Yes, reported here as well: https://github.com/dns-violations/dnsflagday/issues/31

**Comment by kruisdraad** [comment]
ok, thnx, if we can assist, let us know.

good luck

**Comment by vcunat** [comment]
It seems OK now :tada:
