### ISSUE TITLE
minor problems with AWS ?

### ISSUE THREAD

**Issue by kaihendry** [dns-violations/dnsflagday#39]
Just checked my site which IIRC is hosted with AWS Route 53

This report made next to no sense to me:
https://ednscomp.isc.org/ednscomp/b1f7d0d4b6

What am I supposed to do? Raise a support request with AWS?

**Comment by lrosenman** [comment]
That's what I did.... Waiting for reply from AWS Support.

**Comment by Habbie** [comment]
https://www.reddit.com/r/aws/comments/agyyxh/route53_does_not_fully_support_edns_which_may/

> We're working on a fix, and we'll deploy it by March 31, 2019. The fix will ensure that Route 53 will return the appropriate response to DNS queries that include an unrecognized EDNS extension.
