### ISSUE TITLE
Unable to query "cyber.gov.il"

### ISSUE THREAD

**Issue by hank-nuss** [dns-violations/dnsflagday#4]
When testing out https://ednscomp.isc.org/ednscomp the domain "cyber.gov.il" - no results are displayed (FF v60.0.1).  The return URL is:
https://ednscomp.isc.org/ednscomp/3a3bfba668
which when selected shows an error:
cyber.gov.il: no NS records found
But doing nslookup on cyber.gov.il shows:
Header:
   ID=53170, QR=Response, Opcode=QUERY, RCODE=NO ERROR
   Authoritative Answer=No, Truncation=No
   Recursion Desired=Yes, Recursion Available=Yes
   QDCOUNT=1, ANCOUNT=0, NSCOUNT=1, ARCOUNT=0
Question:
   Name=cyber.gov.il, QTYPE=NS, QCLASS=1
Authority Records Section:
- Name=gov.il
    Type=SOA, Class=1, TTL=599 (9 Minutes 59 Seconds), RDLENGTH=46
    Name Server=dns.gov.il, Mailbox=hostmaster.tehila.gov.il
    Serial=2018052902
    Refresh=600 (10 Minutes)
    Retry=200 (3 Minutes 20 Seconds)
    Expire=604800 (7 Days)
    Minimum TTL=3600 (1 Hour)

Something appears to be broken.

-Hank

**Comment by marka63** [comment]
https://ednscomp.isc.org/ednscomp asks for a ZONE name.  cyber.gov.il is not a zone.  It is just a name in a zone.

**Comment by hank-nuss** [comment]
In that case show the error when you return.  The error of no NS records found is hidden until a new browser tab is selected to display the returning URL.
