### ISSUE TITLE
HTML in Markdown?

### ISSUE THREAD

**Issue by r0mflip** [dns-violations/dnsflagday#40]
Is this an expected behavior?

![image](https://user-images.githubusercontent.com/37770235/51388602-006d2f80-1b50-11e9-859d-470b96e3aeae.png)

**Comment by vcunat** [comment]
Hmm, this doesn't happen for me on Firefox 64.x or Chromium 71.x, x86_64-linux.  What's your platform?  Does it always happen?

**Comment by r0mflip** [comment]
Happens to me on Chrome 70, Firefox 64 and Edge on Windows 10 1809.

**Comment by r0mflip** [comment]
And the logos are all off, they span the whole container.

**Comment by Habbie** [comment]
@r0mflip the markdown is rendered correctly on https://dnsflagday.net/, please view the site there!

Leaving this open to see if we can reduce this confusion.

**Comment by huguei** [comment]
Maybe we can add an HTML comment in the markdown, warning users to see the web version? I think those tags will be visible on github but no on the website. Like

`<!-- THIS DOCUMENT IS INTENDED TO BE PROPERLY READ ON https://dnsflagday.net -->`

**Comment by vcunat** [comment]
This _wasn't_ about  https://dnsflagday.net/ ? :astonished:
