### ISSUE TITLE
Add Akamai as supporting organization

### ISSUE THREAD

**Issue by BarryRGreene** [dns-violations/dnsflagday#49]

**Comment by BarryRGreene** [comment]
Catching up inside Akamai. Please add Akamai as a Flag Day supporter. 

Here is our logo. 

![akamai-generic-og-image](https://user-images.githubusercontent.com/14118143/51496303-1e1ade80-1d74-11e9-887a-3e8f273e5bca.jpg)

**Comment by vrisk** [comment]
Hi Barry, the logo file did not upload. Can you try that again?

Vicky

**Comment by BarryRGreene** [comment]
See if this works: https://www.akamai.com/us/en/multimedia/images/open-graph/akamai-generic-og-image.jpg
