### ISSUE TITLE
"without www" can cause confusion

### ISSUE THREAD

**Issue by jezzaaa** [dns-violations/dnsflagday#56]
The web form is misleading, in that it says “without the www”, which is not universally correct. This has caused some confusion, because load-balancer devices are sometimes delegated the “www” as a zone in itself. When we tell someone that their load-balancer is not compliant, they test a zone for themselves but strip the “www” (as instructed by the form), and think they’re OK when in fact they’re not.

Also, the form says to enter the domain name, but really it's only a zone name we should care about. If I put in a non-zone domain name, the failure message correctly tells me that I should put in a zone name.

Perhaps it should say, "Test your zone; Enter zone name (usually without www)" and an extra note to say that rarely, www is a zone in itself, but usually not.

**Comment by vcunat** [comment]
The problem I see is that to laymen it seems rather difficult to explain what "zone" means, and I guess in some cases you need to test multiple zones e.g. due to CNAMEs leading to wherever, which the tool doesn't do for you.

Cross-link: https://github.com/dns-violations/dnsflagday/pull/57
