### ISSUE TITLE
A server which is unreachable from the test site only on one protocol will erroneously report non-compliance

### ISSUE THREAD

**Issue by owendelong** [dns-violations/dnsflagday#58]
If a server is dual-stacked (IPv4, IPv6) and compliant, but for some reason, the test suite can only reach it on one protocol (e.g. IPv6 only or IPv4 only), then the suite will erroneously report the server as completely non-compliant rather than mentioning the real problem that a compliant server is reachable only via one of the two advertised protocols.

**Comment by owendelong** [comment]
The solution to this and #28 are likely related, though from different causes.

**Comment by vcunat** [comment]
Well, that's the same.  Over UDP you can't easily tell _why_ the server doesn't react.  That's actually one of the main points of removing these "EDNS workarounds".

**Comment by pspacek** [comment]
Yes, @vcunat is right. The whole point it so make servers responsive and eliminate timeouts which are hard to deal with.

**Comment by pspacek** [comment]
Okay, now I understand what you mean. We have technical report for fine-grained diagnosis, I think colors in the link should make clear that IPv4 works but IPv6 has all columns red.
