### ISSUE TITLE
Most links to firewall vendors are wrong

### ISSUE THREAD

**Issue by jb-wisemo** [dns-violations/dnsflagday#77]
Some of the links under item "**4. Firewalls must not drop DNS packets**" do not provide any firewall-related information and need to change or move:

- Akamai: The link describes Akamai's own DNS servers (authoritative and recursive) and provides some general information for DNS administrators (sadly missing from the flag day page itself), especially the "N.B. Some third-party vendors" paragraph

- Citrix: The link describes DNS hosting on Citrix hardware/software and admits to a known minor issue but fails to say what it is and why they think it is OK to handle EDNS0 the way they do.  It is unclear to me if the information is about Citrix firewall functions or Citrix DNS server functions.

- BlueCat: The link is all about their own DNS servers, stating that their authoritative servers are compliant and their recursive servers will not enforce the flag day immidiately.

- F5 BIG-IP: Page not found!!!!!

- Google: Describes Google resolver participation in Flag Day

- Juniper: Not a link but actual useful firewall information

- InfoBlox: The link says is all about their own DNS servers, stating that their authoritative servers are compliant and their recursive servers will not enforce the flag day immidiately.

- Azure: Only discusses their own authoritative servers being almost compliant.  No information on Azure resolvers, no information on Azure firewalls, no information on Microsoft DNS software (in their operating systems).

**Comment by pspacek** [comment]
Hello. You are right, it should be called "vendor information", probably in its own section. Feel free to provide pull request.

**Comment by jb-wisemo** [comment]
Sorry, I don't have the software setup to do this quickly, and the flag day itself is already underway in some time zones (Time is now 2018-01-31 15:29 UTC, so Japan and parts of Australia and Russia are already on Feb 1).

**Comment by Habbie** [comment]
> * F5 BIG-IP: Page not found!!!!!

works for me..

**Comment by jb-wisemo** [comment]
Looks like a nice simple fix.

Don't know why the F5 page doesn't work for me, all I get is their custom "Page Not Found" page, using the link https://support.f5.com/csp/article/K07808381?sf206085287=1

**Comment by Habbie** [comment]
> Looks like a nice simple fix.

Thanks, merging it! Thank you for your attention to detail. If you have further concerns, please open a new ticket so we don't lose track.
