### ISSUE TITLE
Unable to build site

### ISSUE THREAD

**Issue by infracritical** [dns-violations/dnsflagday#82]
Call me a 'noob', but...what's next?

I've tried all sorts of commands and get the site built using Jekyll.  Are there any how-to dox for this site?  I'd love to create something useful for the COI.

TIA.

**Comment by Habbie** [comment]
What's the COI? (Will post actual help later.)

**Comment by Mikaela** [comment]
I don't know what you have tried, but have you seen [Setting up your GitHub Pages site locally with Jekyll](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/)?

**Comment by Habbie** [comment]
Makefile:
```
watch:
	docker run --rm -v `pwd`:/srv/jekyll -it jekyll/jekyll jekyll build --watch
```

Gemfile:
```
source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
```

plus `python -mhttp.server` in the `_site` dir that appears once I run make.

**Comment by rad2018x** [comment]
Sorry for the anachronism..."COI" means "Community of Interest".  For the result, thanks...I will try that and post my results here.  I am *very* new to Jekyll, and from what I've read and have done thus far with it, it is an *awesome* tool!  Again, many thanks!!!  :)

**Comment by infracritical** [comment]
OK...I checked if I needed 'docker'...I don't.  So...the second step involving building the Gemfile, worked.

Here's what I had done:

* cd /webdev/devsite1
* git clone https://github.com/dns-violations/dnsflagday.git
* cd dnsflagday
* vi Gemfile (then add the items from Step 2 outlined above)
* bundle install
* (wait about 2-3 minutes before everything is installed)
* bundle exec jekyll build
* (get the following error message, but the build still works...)

GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.

* bundle exec jekyll serve
* (get the same error message, but the serve still works...)
* (access my broswer, enter "http://localhost:4000" for the URL, and bada bing, bada boom...)

This is assuming that:

* Ruby is already installed; and,
* Jekyll is already installed

In my case, I had both (sorry...should've specified that).

In any circumstance, thank you all for your help!!!

**Comment by Habbie** [comment]
Ah, thanks for the non-Docker instructions!

**Comment by rad2018x** [comment]
You (and whoever else reads this thread) are most welcome.  ;)
