### ISSUE TITLE
[discussion] mandatory TCP support on server side

### ISSUE THREAD

**Issue by pspacek** [dns-violations/dnsflagday#89]
User-oriented description why TCP is important: https://kb.isc.org/docs/aa-01219

Specification: https://tools.ietf.org/html/rfc7766

Expected advantages:
* More reliable name resolution.
* Getting rid of long timeouts on client side caused by too big UDP answers.
* Getting rid of EDNS buffer size guessing/heuristics on client side (i.e. less roundtrips!).
After implementation of this change clients could reliably use EDNS buffer size which does not cause UDP fragmentation and use TCP for oversized answers.

Expected disadvantages:
* Standard compliant server implementations which already support TCP: None
* Non-compliant server implementations: Have to invest resources into TCP implementation.
* In general: Some increase in TCP usage and resource consumption. Please note that number of clients switching to TCP depends on EDNS buffer sizes so it may vary for multiple reasons over time.

Expected implementation complexity for software developers:
* Standards compliant client implementations: None
* Non-compliant implementations which are missing TCP support: High

Expected non-compliance: TBD link to research by APNIC

Research to confirm assumptions: TBD

**Comment by vcunat** [comment]
[operational requirements draft](https://tools.ietf.org/html/draft-ietf-dnsop-dns-tcp-requirements) at dnsop (thanks to Sara)

**Comment by jaredmauch** [comment]
I was discussing with someone last week at IETF that it would be interesting to have configurable knobs in software that would just respond to 1:X queries with TC=1.  This would allow for this to gradually be rolled out.  With queries moving to TCP with other transports (DoH/DoT) it would be helpful to do this to determine who may not have enough state (or other issues) to handle the additional load.

**Comment by vcunat** [comment]
I can imagine that as a simple BPF program.  The advantage is both in performance and in the fact that you implement it once independently of what DNS server you use.

**Comment by pspacek** [comment]
FYI Knot DNS already has it:
https://www.knot-dns.cz/docs/2.9/singlehtml/#noudp-no-udp-response

**Comment by pspacek** [comment]
I believe this was covered by DNS Flag Day 2020.
